### ISSUE TITLE
Invalid close codes in protocol

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#110]
From the [WebSocket spec](https://www.w3.org/TR/websockets/#websocket):

> The close() method must run the following steps:
> 1. If the method's first argument is present but is not an integer equal to 1000 or in the range 3000 to 4999, throw an InvalidAccessError exception and abort these steps.

Close code 1001 is still in [RFC 6455](https://tools.ietf.org/html/rfc6455#section-7.4.1) though. Is that only an internal close code?

Our close codes:

1001: Going Away
1002: No Shared Subprotocol Found
(...)

Steps to reproduce:

    ws = new WebSocket('wss://server.saltyrtc.org:9287')
    ws.close(1002)

We should probably change our protocol accordingly.

@lgrahl RFC

**Comment by dbrgn** [comment]
More information here: https://stackoverflow.com/questions/22587438/websocket-close-code-1002#22589089

> Errors 1002 are usually generated by the internals of a WebSocket implementation, not an application using WebSocket.

And furthermore, we should probably change our 3xxx range to 4xxx:

    3000-3999

      Status codes in the range 3000-3999 are reserved for use by
      libraries, frameworks, and applications.  These status codes are
      registered directly with IANA.  The interpretation of these codes
      is undefined by this protocol.

    4000-4999

      Status codes in the range 4000-4999 are reserved for private use
      and thus can't be registered.  Such codes can be used by prior
      agreements between WebSocket applications.  The interpretation of
      these codes is undefined by this protocol.

https://tools.ietf.org/html/rfc6455#section-7.4.2

**Comment by lgrahl** [comment]
No, the close codes `1001` and `1002` are valid. The server will use these close codes implicitly from the underlying WebSocket implementation:
* `1001` in case the server is being closed.
* `1002` in case no shared sub-protocol could be found / (WebSocket) protocol error.

Note: This is not in our hands. WebSocket simply behaves that way.

I've deliberately chosen the `3000` range because SaltyRTC is a library. I do not want to use the `4000` range. But yes, technically we would have to register these status code at IANA. We can still choose to do that at some point.

**Comment by dbrgn** [comment]
> Only if the server chose the subprotocol above, this protocol SHALL be applied. If another shared subprotocol that is not related to SaltyRTC has been found, continue with that subprotocol. Otherwise, close the connection to the server with a close code of 1002 (No Shared Subprotocol Found).

From our spec. This is not possible in the browser.

> A client who sends a 'close' message MUST set the reason field to a valid close code (as enumerated in Close Code Enumeration). 1001 SHALL be used for normal close cases. Once the message has been sent, the client SHALL remove all cached data (such as cookies and sequence numbers) of and for the other client. The client SHALL also terminate the connection to the server with a close code of 1001 (Going Away) if the connection is still open.

This isn't possible either.

**Comment by dbrgn** [comment]
> But yes, technically we would have to register these status code at IANA.

Looks like so far nobody did so? https://www.iana.org/assignments/websocket/websocket.xml#table-close-code-number-range

**Comment by lgrahl** [comment]
First of all, I didn't know the W3C API prohibits the use of `1000` close codes. Personally, I don't see the need to prohibit the user from using them. But they chose to do so anyway which is unfortunate.

The first example is done implicitly by WebSocket because no sub-protocol could be found. There's no need to do that by hand. We can change the last sentence to:
> Otherwise, the connection to the server should close automatically. If not, the connection to the server MUST be closed. The close code SHOULD be `1002` (No Shared Subprotocol Found).

We could simply change the text of the second example to:
> The client SHALL also terminate the connection to the server if the connection is still open. In this case, the close code SHOULD be `1001` (Going Away).

Yes, nobody has registered any close codes so far. I've taken this list into account during specification.

**Comment by dbrgn** [comment]
> We can change the last sentence to

I'd simply append the following sentence instead:

> Note that this is normally handled by the WebSocket implementation.

And regarding this:

> The client SHALL also terminate the connection to the server if the connection is still open. In this case, the close code SHOULD be 1001 (Going Away).

Isn't a `close` event actually a "normal" closing event? The 1001 code (going away) is used when navigating away from a page without explicitly closing, but in our case we *are* explicitly closing the connection in a normal way. I think `1000 CLOSE_NORMAL` might actually be the better code in this case.

**Comment by lgrahl** [comment]
Mh, we can just leave out closing for the first case. If the server doesn't close, one of the sub-protocols has been negotiated. Otherwise, it simply doesn't work.

Second case: Yeah, just close, fair enough.

Edit: Will fix it later this day.
