### ISSUE TITLE
End of Candidates

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#118]
The current WebRTC task spec does not allow to send `null` to indicate that no more candidates will be sent (until an ICE restart occurs).

Suggesting to allow `null` in the *candidate* field of the 'candidates' message.

**Comment by dbrgn** [comment]
Should we maybe be more explicit about the end-of-candidates? After all, the null candidate could also be the result of a bug.

On the other hand, null wouldn't require any format update, so it's the pragmatic approach. And it matches the behavior of the browser.

**Comment by lgrahl** [comment]
I'd love to be more explicit but I think it's not worth the effort. Allowing `null` is an okay compromise for me. (ORTC is a lot more explicit)

**Comment by dbrgn** [comment]
I discovered an issue with this.

- According [to the spec](https://www.w3.org/TR/webrtc/#dom-rtcpeerconnectioniceevent), the entire `candidate` field returned by `onicecandidate` "is set to null when an event is generated to indicate the end of candidate gathering".
- On the other side of the connection buildup process, [addIceCandidate](https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-addicecandidate()) is nullable according to the spec. However, at least the Java bindings don't support null candidates.
- The rest of [that part of the spec](https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-addicecandidate()) seems to use different semantics than a `null` candidate:
  - The description mentions: `This method can also be used to indicate the end of remote candidates when called with an empty string for candidate`.
  - It also mentions, in step 4.6: `If candidate.candidate is an empty string, process candidate as an end-of-candidates indication for the corresponding media description and ICE candidate generation`.

I propose to revert this change and to use empty strings for the `candidate` field in order to indicate end-of-candidates. This requires some code change for the users of the library, but that's fine.

**Comment by lgrahl** [comment]
Let's stick with it for now until we find out what they really intended and whether or not we need to be backwards compatible: https://github.com/w3c/webrtc-pc/issues/1077
I'm pretty sure we will have to keep this change to ensure backwards compatibility.

By the way, they've also changed the attribute types and values for `RTCIceCandidateInit` and we'll need to update the task for that: https://rawgit.com/w3c/webrtc-pc/master/webrtc.html#dom-rtcicecandidateinit

Edit: If the Java bindings don't accept `null` but do accept empty string of `candidate.candidate`, then I think the task or the implementation has to implement a workaround. I want to stick with the official API.

**Comment by dbrgn** [comment]
> Let's stick with it for now until we find out what they really intended and whether or not we need to be backwards compatible

In either case the user will have to do a simple check before sending the candidate through SaltyRTC. But if we want to accept null values as candidates, that adds multiple conditional checks in the task code. If possible, I'd prefer to remove that, especially since adding null candidates as remote candidates doesn't seem to be supported by the specification (and the Java implementation reflects that).

In doubt, choose the simpler version. Don't you think?

If you prefer, I can also add a "sendEndOfCandidates()" method to the task that automatically sends an empty candidate.

**Comment by lgrahl** [comment]
I don't understand why the user would have to do a check before sending the candidate?

Adding `null` candidates as remote candidates was absolutely fine beforehand. I don't know why it doesn't work anymore (or if it ever worked for the Java binding - that would be a bug). So, let's wait how this issue is going to be addressed by the spec members.

Again, we want to be spec compatible. If the Java binding or any other binding isn't WebRTC spec compatible, that should not be a concern for our specification.

> If you prefer, I can also add a "sendEndOfCandidates()" method to the task that automatically sends an empty candidate.

That will probably not work as the other two fields would be missing.

**Comment by dbrgn** [comment]
> Adding null candidates as remote candidates was absolutely fine beforehand.

I don't know whether it worked, I never did that in my code so far (since I only sent candidates through SaltyRTC if they were non-null).

> Again, we want to be spec compatible.

The spec clearly seems to say that adding a remote candidate with `candidate` set to an empty string and the other values set to `null` indicates the end of candidates ([addIceCandidate algorithm](https://www.w3.org/TR/webrtc/#dfn-addicecandidate), step 4.6).

> So, let's wait how this issue is going to be addressed by the spec members.

Will it be addressed?

**Comment by lgrahl** [comment]
Yes, I understand your point but it was `null` for the whole object before to indicate the end of candidates and they will probably not break backwards compatibility in their API. So, I assume both will be valid. Reverting the changes from our side would break that backwards compatibility.

> Will it be addressed?

I don't know: https://github.com/w3c/webrtc-pc/issues/1077

**Comment by dbrgn** [comment]
For the record, the spec specifies an end-of-candidates indication like this:

> "If this RTCIceCandidate represents an end-of-candidates indication, candidate is an empty string."

https://www.w3.org/TR/webrtc/#dom-rtcicecandidate-candidate

We should fix to the (latest) spec and not support deprecated "features".

**Comment by lgrahl** [comment]
The discussion in https://github.com/w3c/webrtc-pc/issues/1077 revealed that we still have to support `null` as it has a different meaning than the new end-of-candidate events (which are end-of-candidate events towards specific media streams).

There are two options:
1. We re-add the `null` case, or
2. The SaltyRTC implementation has to keep track of media streams and raise `null` once all end-of-candidate events came in

I strongly prefer 1. as 2. seems very error-prone.

**Comment by dbrgn** [comment]
After reading the discussion I'm still confused both how to design SaltyRTC but also how to use WebRTC with regard to end-of-candidates messages.

Will https://github.com/w3c/webrtc-pc/issues/1077 result in a discussion that might change things for us, or is the fact that `null` must be supported final? If yes, I'd also vote for 1 instead of 2.

**Comment by lgrahl** [comment]
You're not alone. This is pretty confusing to me as well. It looks like this will be discussed (if I interpret the label correctly), so we can wait until it is being resolved. However, I guess the outcome will be that `null` will still be used in the `onicecandidate` event for non-Trickle-ICE implementations. The only question is what `addIceCandidate` does with `null` but that shouldn't concern us.

**Comment by dbrgn** [comment]
Ok, so back to allowing `null` in that case?

**Comment by lgrahl** [comment]
Yes... for now I guess.

**Comment by lgrahl** [comment]
Re-added `Nil` in e7b9491a7000f5fbf89c53f25dc1c0b8026fcee8 but I'll leave this open until I get a final response on https://github.com/w3c/webrtc-pc/issues/1077

**Comment by lgrahl** [comment]
Okay, so this is the outcome: There will be `null` from the `onicecandidate` event (W3C spec) once gathering is complete, so `Nil` will remain as some applications may need this infomation (non-browser implementations for example). Even though you may need to filter `null` as you can't pass it to `addIceCandidate` (W3C spec) directly.
