### ISSUE TITLE
onIceCandidatesRemoved

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#133]
Should we support this event in our protocol, @lgrahl?

**Comment by lgrahl** [comment]
Not specified officially and I don't know what it's supposed to indicate.
Can you elaborate? Do you need it?

**Comment by dbrgn** [comment]
The WebRTC implementation throws that event when an ICE candidate is not valid anymore.

Say you switch from 3G to WiFi. Then the candidates connected to the 3G connectivity will not be valid anymore and should not be used by the other side anymore.

It could be this draft that initially specified this: https://datatracker.ietf.org/doc/draft-thatcher-ice-remove-candidate/ Not sure if it was merged into the main specification.

I couldn't find any docs in the MDN about it. Maybe it's not in the web API yet, or not (yet?) standardized? Here's the code: https://chromium.googlesource.com/external/webrtc/+/master/webrtc/pc/peerconnection.cc#1577

**Comment by lgrahl** [comment]
So, I'm assuming this is related to continuous gathering which is
proprietary at the moment (and I'm not expecting it in 1.0 any more since
they are pushing towards a release). I'm pretty sure the RTCWeb group
hasn't decided on which approach to take for the *walk out of the door
problem*, see:
https://www.ietf.org/proceedings/94/slides/slides-94-ice-6.pdf

We can add it once it's specified. If you have a use case right now and you
need it, forking the task to maybe *webrtc-experimental* is fine by me.

**Comment by dbrgn** [comment]
> So, I'm assuming this is related to continuous gathering which is proprietary at the moment

Ah, that's possible.

> We can add it once it's specified.

Agree!

**Comment by lgrahl** [comment]
I'll close this for now.
