### ISSUE TITLE
Add trusted key storage description

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-meta#20]
We should add a short recommendation for storing and finding trusted keys.

**Comment by lgrahl** [comment]
@dbrgn If you have suggestions from the existing implementations, let me know. :)

**Comment by dbrgn** [comment]
Storing keys is not yet implemented :) I can add notes about it once I'll get to it, but it's not yet the main priority as long as I'm still in development/testing mode.

**Comment by dbrgn** [comment]
In the browser, we'll probably ask the user for a password in order to store the keys. The permanent keystore as well as the peer public key will then be encrypted using `nacl.secretbox(data, password)` and stored in local browser storage.

I can try to come up with a description for the spec. We probably don't need to go into detail, but we need to specify _what_ to store and _how_ to store it securely.

**Comment by dbrgn** [comment]
Note to self: The own public key does not need to be stored, it can be derived from the private key using nacl.

**Comment by dbrgn** [comment]
We since implemented trusted keys using nacl secretbox crypto with a user provided password in browser local storage, but I don't think we should give recommendations on how to store the trusted keys. It probably depends a lot on the use case. My suggestion is that every application should deal with this appropriately, but without any concrete recommendations from us.

I think the section that's already in the protocol should be sufficient:

> Once the authentication process of the two clients has been completed (after both clients have sent each other a valid 'auth' message), the clients MAY choose to trust each other by storing each other's public key and the path securely (note, that this trusting procedure must be handled by the application).

@lgrahl do you agree, can we close this?

**Comment by lgrahl** [comment]
Agree.
