### ISSUE TITLE
Prevent DataChannel ID reuse

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-meta#35]
We already discussed this sometime, but the discussion was probably not in this issue tracker.

When creating data channels in the browser, the id increments for each new channel. According to a few quick tests I did, once it reaches 1023 every new data channel will get the id 1023.

We should verify whether that's really true and then find out whether there's a way to prevent that behavior.

**Comment by lgrahl** [comment]
If it happens, this is definitely a bug and we should report it (I'll try it out soon). Still, if it happens we can't really prevent it because the `RTCPeerConnection` instance is not under our control. What we can do is prevent nonce reuse for wrapped data channels - in fact this can be done very easily:

```
def wrap_data_channel(self, data_channel):
    if data_channel.id in self.wrapped_data_channels:
        raise ValueError('Data channel id reused')
    ...
```

But you are right, the check needs to be part of the spec (or of the task's spec).

**Comment by lgrahl** [comment]
- Issue in the Chromium implementation (does allocate n-1 streams, not n): [Link](https://bugs.chromium.org/p/chromium/issues/detail?id=619849&q=dbrgn&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) (seems to be [fixed](https://chromium.googlesource.com/external/webrtc/+/1d7a637340ea097ea55061af7b566ceccc2678c8), need to have a look in which version it actually landed)
- Issue in the WebRTC WebIDL spec: https://github.com/w3c/webrtc-pc/issues/746

I have added a MUST to the spec to check that a data channel id is not already taken by an _open_ data channel.
